# Generated by Django 6.0.1 on 2026-01-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0002_profile_report_delete_lostfounditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_matches', to='lostfound.report')),
                ('lost_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='lostfound.report')),
            ],
        ),
    ]
