# Generated by Django 6.0.1 on 2026-01-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
    ]
