# Generated by Django 6.0.1 on 2026-01-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0004_report_is_matched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found'), ('RETURNED', 'Returned')], max_length=20),
        ),
    ]
