# Generated by Django 6.0.1 on 2026-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0006_match_approved_at_match_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('WALLET', 'Wallet'), ('PHONE', 'Phone'), ('BAG', 'Bag'), ('LAPTOP', 'Laptop'), ('BOOKS', 'Books'), ('USB', 'USB Drive'), ('OTHERS', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='item_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
