# Generated by Django 6.0.1 on 2026-01-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0007_report_image_public_id_alter_report_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
