# Generated by Django 6.0.1 on 2026-02-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0008_match_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], max_length=10),
        ),
    ]
